version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.9
    - 1.4.0
    - 1.4.1
    - 1.5.0
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: css-loader
    versions:
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: hugo-bin
    versions:
    - 0.69.0
  - dependency-name: file-loader
    versions:
    - 6.2.0
  - dependency-name: webpack
    versions:
    - 4.46.0
    - 5.25.0
    - 5.25.1
  - dependency-name: assets-webpack-plugin
    versions:
    - 6.1.2
  - dependency-name: postcss-import
    versions:
    - 14.0.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: "@babel/register"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.13.0
    - 7.13.8
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: copy-webpack-plugin
    versions:
    - 6.4.1
  - dependency-name: webpack-merge
    versions:
    - 5.7.3
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: postcss-loader
    versions:
    - 4.2.0
